//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HalloEF_ModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abteilung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Abteilung()
        {
            this.Mitarbeiter = new HashSet<Mitarbeiter>();
            this.Board = new Rechteck();
        }
    
        public int Id { get; set; }
        public string Bezeichnung { get; set; }
    
        public Rechteck Board { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mitarbeiter> Mitarbeiter { get; set; }
    }
}
