//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HalloEF_ModelFirst
{
    using System;
    
    public partial class Rechteck
    {
        public double Länge { get; set; }
        public double Breite { get; set; }
        public string Farbe { get; set; }
    }
}
